title: 方一雄
description: My Personal Blog
author: Fang
logo: /static/img/avatar.png
github: https://github.com/FangYiXiong
about: 一个独立的人的独立博客

baseurl: "https://fangyixiong.github.io/blog_demo/"
url: "https://fangyixiong.github.io/blog_demo/"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
